"""empty message

Revision ID: 6e318ea63f53
Revises: 19ca6699c617
Create Date: 2022-09-21 08:54:06.017384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e318ea63f53'
down_revision = '19ca6699c617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_created')
    # ### end Alembic commands ###
